### PR TITLE
Budget API implementation

### PR DESCRIPTION
**Pull request by anar-a**
The functions for manipulating user budgets

### CODE REVIEW

**Comment by anar-a** [comment]
PLEASE APPROVE AFTER THOROUGH REVIEW (of course)

**Comment by LukeRagan** [comment]
looks good <3

**Review by LukeRagan — COMMENTED** [review]
It all looks good to me

**Review by LukeRagan — APPROVED** [review]
OK now it looks good

**Comment by anar-a** [comment]
Thank you Luke Ragan

**Comment by anar-a** [comment]
I meant to merge and then close this.

**Pull request merged**
